"""
Django settings for peercheck project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a29z8fjb^1pcdcx9^qo=@ikm_kpsxu8kmxh&(1xv7*)r70&cd+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '127.0.0.1', 'localhost','https://api.hask.app','http://192.168.56.1:8000',' 172.16.16.126']

# Custom user model
AUTH_USER_MODEL = "api.UserProfile"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'knox',

    'api',
    'drf_spectacular', # Added for OpenAPI schema generation
]

SPECTACULAR_SETTINGS = {
    'TITLE': 'PeerCheck API',
    'DESCRIPTION': 'API for the PeerCheck application, providing operations for SOPs, audio processing, sessions, feedback, and user management.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, # Usually False for Swagger UI/ReDoc
}

# REST framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'knox.auth.TokenAuthentication',  # Knox token-based authentication
        'rest_framework.authentication.SessionAuthentication',  # For sessions
        'rest_framework.authentication.BasicAuthentication',  # For basic auth
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Knox-specific settings
REST_KNOX = {
    # # 'SECURE_HASH_ALGORITHM': 'cryptography.hazmat.primitives.hashes.SHA256',
    # 'SECURE_HASH_ALGORITHM': 'hashlib.sha512',
    'AUTH_TOKEN_CHARACTER_LENGTH': 8,
    'TOKEN_TTL': timedelta(minutes=120),
    'USER_SERIALIZER': 'knox.serializers.UserSerializer',
    'TOKEN_LIMIT_PER_USER': None,
    'AUTO_REFRESH': False,
}

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Enable CORS
    'django.middleware.gzip.GZipMiddleware',
]

ROOT_URLCONF = 'peercheck.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'peercheck.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'rag_3pc_check.sqlite3',
    },
    'development': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'peercheck_dev',
        'USER': 'postgres',
        'PASSWORD': 'QP3HeJel62BPzPaq07uETezy',
        'HOST': 'e-commerce.cj3oddyv0bsk.us-west-1.rds.amazonaws.com',
        'PORT': '5432',
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Password hashers
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'uploads'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS configuration
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True  # Enable all origins for development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://localhost:4222",
    "http://localhost:4400",
    "http://127.0.0.1:8000",
    'https://api.hask.app',
    'https://peercheck.hask.app',
    'http://192.168.56.1:8000',
    'http://172.16.16.126:8000',
    'http://172.16.16.126:5000'
]
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:4200',
    "http://localhost:4222",
    "http://localhost:4400",
    'http://13.52.99.241:80',
    'https://api.hask.app',
    'https://peercheck.hask.app',
    'http://192.168.56.1:8000',
    'http://172.16.16.126:8000',
    'http://172.16.16.126:5000'
]
CORS_ALLOW_METHODS = ['DELETE', 'OPTIONS', 'PATCH', 'GET', 'POST', 'PUT']
CORS_ALLOW_HEADERS = [
    'accept', 'accept-encoding', 'authorization', 'content-type', 'dnt', 
    'origin', 'user-agent', 'x-csrftoken', 'x-requested-with'
]

AWS_S3_ACCESS_KEY_ID = ''
AWS_S3_SECRET_ACCESS_KEY = ''
AWS_STORAGE_BUCKET_NAME = ''
AWS_S3_REGION_NAME = ''

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB

# Audio processing settings
WHISPER_MODEL = "small.en"
ALLOWED_TEXT_EXTENSIONS = {'pdf', 'docx', 'txt'}
ALLOWED_AUDIO_EXTENSIONS = {'mp3', 'wav', 'm4a', 'mpeg', 'mp4'}

# Hugging Face Token
HF_TOKEN =''

# DGX / GPU Settings
USE_DGX = os.getenv("USE_DGX", "False").lower() == "true"
OLLAMA_API_BASE = os.getenv("OLLAMA_API_BASE", "http://localhost:11434")

# Local LLM Configuration (Llama 3.1 on DGX or similar)
# Prefer LOCAL_LLM_BASE_URL as per implementation_plan.md, but fall back to legacy env var.
LOCAL_LLM_BASE_URL = os.getenv(
    "LOCAL_LLM_BASE_URL",
    os.getenv("LOCAL_LLM_API_BASE", "https://ollama.com/"),
)

# Backwards-compat alias for any existing references
LOCAL_LLM_API_BASE = LOCAL_LLM_BASE_URL

LOCAL_LLM_API_KEY = os.getenv(
    "LOCAL_LLM_API_KEY",
    "",  # Often "EMPTY" for local non-gated models
)
LOCAL_LLM_MODEL = os.getenv(
    "LOCAL_LLM_MODEL",
    "gpt-oss:120b",  # Or "llama3.1" depending on server
)


if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    RAGITIFY_BASE_URL = os.getenv("RAGITIFY_BASE_URL", "http://localhost:5000/").rstrip("/")
elif DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql_psycopg2' and DATABASES['default']['NAME'] == 'peercheck_dev':
    RAGITIFY_BASE_URL = os.getenv("RAGITIFY_BASE_URL", "https://rag.xamplify.co/").rstrip("/")
else:
    RAGITIFY_BASE_URL = os.getenv("RAGITIFY_BASE_URL", "http://localhost:8000/").rstrip("/")

# --- RAGitify Plug-and-Play ---
RAGITIFY_ENABLED = os.getenv("RAGITIFY_ENABLED", "false").lower() == "true"
RAGITIFY_TIMEOUT_SECONDS = int(os.getenv("RAGITIFY_TIMEOUT_SECONDS", "30"))
RAGITIFY_DEFAULT_PASSWORD = os.getenv("RAGITIFY_DEFAULT_PASSWORD", "ChangeMe!123")

RAGITIFY_PATHS = {
    # Auth
    "register": "/rag/register/",
    "login": "/rag/login/",
    "protected": "/rag/protected/{token}/",

    # Vector stores
    "vector_store_create": "/rag/vector-store/{token}/",
    "vector_store_list": "/rag/vector-store/{token}/list/",
    "vector_store_detail": "/rag/vector-store/{token}/{id}/",

    # Documents
    "document_ingest": "/rag/document/{token}/ingest/",
    "document_list": "/rag/document/{token}/list/",
    "document_detail": "/rag/document/{token}/{id}/",
    "document_status": "/rag/document/{token}/{document_id}/status/",

    # Assistants
    "assistant_create": "/rag/assistant/{token}/",
    "assistant_list": "/rag/assistant/{token}/list/",
    "assistant_detail": "/rag/assistant/{token}/{id}/",

    # Threads
    "thread_create": "/rag/thread/{token}/",
    "thread_list": "/rag/thread/{token}/list/",
    "thread_detail": "/rag/thread/{token}/{id}/",
    "thread_messages": "/rag/thread/{token}/{thread_id}/messages/",

    # Messages
    "message_create": "/rag/message/{token}/",
    "message_list": "/rag/message/{token}/list/",
    "message_detail": "/rag/message/{token}/{id}/",

    # Runs
    "run_create": "/rag/run/{token}/",
    "run_list": "/rag/run/{token}/list/",
    "run_detail": "/rag/run/{token}/{id}/",
    "run_submit_tool_outputs": "/rag/run/{token}/{run_id}/submit-tool-outputs/",
}
