# Generated by Django 5.2.4 on 2025-07-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='session',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='processing_session',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('audio_upload', 'Audio Upload'), ('feedback_submit', 'Feedback Submit'), ('sop_create', 'SOP Create'), ('sop_update', 'SOP Update'), ('sop_delete', 'SOP Delete'), ('audiofile_delete', 'AudioFile Delete'), ('feedback_update', 'Feedback Update'), ('feedback_delete', 'Feedback Delete'), ('review_submit', 'Review Submit'), ('feedbackreview_update', 'FeedbackReview Update'), ('feedbackreview_delete', 'FeedbackReview Delete'), ('userprofile_update', 'UserProfile Update'), ('userprofile_delete', 'UserProfile Delete')], max_length=50),
        ),
    ]
