# Generated by Django 5.2.6 on 2025-10-03 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_auditlog_session_audiofile_processing_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('vector_store_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAGMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('thread_external_id', models.CharField(db_index=True, max_length=128)),
                ('role', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAGRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('thread_external_id', models.CharField(db_index=True, max_length=128)),
                ('assistant_external_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAGThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('assistant_external_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='rag_document_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='rag_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='rag_ingested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='rag_last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='rag_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='rag_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='rag_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referencedocument',
            name='rag_vector_store_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='RAGAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rag_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
