# Generated by Django 5.2.6 on 2025-10-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ragassistant_ragmessage_ragrun_ragthread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragaccount',
            name='vector_store_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
