# Generated by Django 5.1.6 on 2025-05-29 08:49

from django.db import migrations, models
import json

def clean_invalid_transcription(apps, schema_editor):
    AudioFile = apps.get_model('api', 'AudioFile')
    for audio_file in AudioFile.objects.filter(transcription__isnull=False):
        try:
            # Attempt to parse the transcription as JSON
            json.loads(audio_file.transcription)
        except (TypeError, ValueError):
            # Set invalid transcription to NULL
            audio_file.transcription = None
            audio_file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_systemsettings_auditlog_usersettings'),
    ]

    operations = [
        migrations.RunPython(clean_invalid_transcription),
        migrations.AlterField(
            model_name='audiofile',
            name='transcription',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
