# Generated by Django 5.1.6 on 2025-05-29 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_session_status_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_files_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
