# Generated by Django 5.2.1 on 2025-05-29 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_audiofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('audio_upload', 'Audio Upload'), ('feedback_submit', 'Feedback Submit'), ('sop_create', 'SOP Create'), ('sop_update', 'SOP Update'), ('sop_delete', 'SOP Delete'), ('audiofile_delete', 'AudioFile Delete'), ('feedback_update', 'Feedback Update'), ('feedback_delete', 'Feedback Delete'), ('review_submit', 'Review Submit'), ('feedbackreview_update', 'FeedbackReview Update'), ('feedbackreview_delete', 'FeedbackReview Delete'), ('userprofile_update', 'UserProfile Update'), ('userprofile_delete', 'UserProfile Delete'), ('session_status_update', 'Session Status Update'), ('session_update', 'Session Update'), ('session_delete', 'Session Delete')], max_length=50),
        ),
    ]
