# Generated by Django 5.2 on 2025-06-01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_feedback_created_at_feedback_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

