# Generated by Django 5.2.1 on 2025-06-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_speakerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
