# Generated by Django 5.2.4 on 2025-07-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_speakerprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
