# Generated by Django 5.2.4 on 2025-07-23 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_audiofile_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='audiofile',
            name='coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='report_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('sop', 'Standard Operating Procedure'), ('procedure', 'Procedure Document'), ('manual', 'Manual'), ('guideline', 'Guideline'), ('checklist', 'Checklist'), ('other', 'Other')], default='sop', max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('upload_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reference_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_words', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('coverage', models.FloatField(default=0.0)),
                ('processed_docx_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.audiofile')),
                ('reference_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.referencedocument')),
            ],
        ),
        migrations.AddField(
            model_name='audiofile',
            name='reference_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_comparisons', to='api.referencedocument'),
        ),
    ]
