# Generated by Django 5.2.4 on 2025-07-19 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_audiofile_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('audio_upload', 'Audio Upload'), ('document_upload', 'Reference Document Upload'), ('document_process', 'Reference Document Process'), ('document_delete', 'Reference Document Delete'), ('feedback_submit', 'Feedback Submit'), ('sop_create', 'SOP Create'), ('sop_update', 'SOP Update'), ('sop_delete', 'SOP Delete'), ('audiofile_delete', 'AudioFile Delete'), ('feedback_update', 'Feedback Update'), ('feedback_delete', 'Feedback Delete'), ('review_submit', 'Review Submit'), ('feedbackreview_update', 'FeedbackReview Update'), ('feedbackreview_delete', 'FeedbackReview Delete'), ('userprofile_update', 'UserProfile Update'), ('userprofile_delete', 'UserProfile Delete'), ('session_status_update', 'Session Status Update'), ('session_update', 'Session Update'), ('session_delete', 'Session Delete')], max_length=50),
        ),
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('sop', 'Standard Operating Procedure'), ('procedure', 'Procedure Document'), ('manual', 'Manual'), ('guideline', 'Guideline'), ('checklist', 'Checklist'), ('other', 'Other')], default='sop', max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('upload_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reference_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sop',
            name='reference_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_sops', to='api.referencedocument'),
        ),
    ]
