# Generated by Django 5.2.4 on 2025-07-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_audiofile_options_audiofile_coverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
