# Generated by Django 5.2.4 on 2025-07-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_audiofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='diarization',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
